name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install the dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm i

      - name: Build projects
        run: npm run build

      - name: Deploy Storybook
        # This needs an Acces Token stored as "GH_TOKEN" 👇
        run: |
            npm install
            npm run deploy-storybook -- --ci
        env:
            GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
            branch: gh-pages
            folder: packages/docs/storybook-static