name: Deploy docs

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install
        run: |
          rm -rf node_modules package-lock.json
          rm -rf packages/docs/docs-build packages/docs/node_modules
          npm i

      - name: Build
        run: npm run build

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=docs-build
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.MY_GITHUB_TOKEN }}